const jobs = {
    "squire-ramza": { "name": "見習い戦士", "action": "ガッツ" },
    "squire": { "name": "見習い戦士", "action": "基本技" },
    "chemist": { "name": "アイテム士", "action": "アイテム" },
    "knight": { "name": "ナイト", "action": "戦技" },
    "archer": { "name": "弓使い", "action": "チャージ" },
    "monk": { "name": "モンク", "action": "拳術" },
    "oriest": { "name": "白魔道師", "action": "白魔法" },
    "wizard": { "name": "黒魔道士", "action": "黒魔法" },
    "time-mage": { "name": "時魔道士", "action": "時魔法" },
    "summoner": { "name": "召喚士", "action": "召喚魔法" },
    "thief": { "name": "シーフ", "action": "盗む" },
    "oracle": { "name": "陰陽士", "action": "陰陽術" },
    "mediator": { "name": "話術士", "action": "話術" },
    "geomancer": { "name": "風水士", "action": "風水術" },
    "lancer": { "name": "竜騎士", "action": "ジャンプ" },
    "samurai": { "name": "侍", "action": "引き出す" },
    "ninja": { "name": "忍者", "action": "投げる" },
    "calculator": { "name": "算術士", "action": "算術" },
    "bard": { "name": "吟遊詩人", "action": "詩う" },
    "dancer": { "name": "踊り子", "action": "踊る" },
    "mime": { "name": "ものまね士", "action": "なし" },
}
